// Renders the "static review surface vs execution surface" Markdown for a
// testbed PR: what a diff reviewer sees (lines/files changed) next to what
// the run actually did (packages installed, processes recorded, outbound
// destinations) per the Garnet/Jibril execution record.
//
// Facts only — no verdicts. The Garnet Runtime Review comment on the PR is
// the authoritative runtime record; this table quantifies the gap between it
// and the reviewable diff.
//
// Env:
//   PROFILE_PATH   — Jibril profile JSON exported by the record job (optional)
//   LOCKFILE_PATH  — package-lock.json generated by the install (optional)
//   DIFF_NUMSTAT   — output of `git diff --numstat <base>...<head>` (required)
//   DIFF_PATCH_PATH — file containing the full `git diff <base>...<head>` patch
//                     (optional; used to check which recorded domains appear
//                     in the changed content)
//   HEAD_SHA       — PR head SHA (optional, for provenance line)
// Prints Markdown to stdout.
import { readFile } from "node:fs/promises"

async function readJsonMaybe(path) {
  if (!path) return null
  try {
    return JSON.parse(await readFile(path, "utf8"))
  } catch {
    return null
  }
}

async function readTextMaybe(path) {
  if (!path) return ""
  try {
    return await readFile(path, "utf8")
  } catch {
    return ""
  }
}

const profile = await readJsonMaybe(process.env.PROFILE_PATH)
const lockfile = await readJsonMaybe(process.env.LOCKFILE_PATH)
const numstat = (process.env.DIFF_NUMSTAT || "").trim()
const patch = await readTextMaybe(process.env.DIFF_PATCH_PATH)

// --- static review surface: the diff ---
let added = 0
let deleted = 0
const files = []
for (const line of numstat ? numstat.split("\n") : []) {
  const [a, d, file] = line.split("\t")
  if (!file) continue
  added += Number(a) || 0
  deleted += Number(d) || 0
  files.push(file)
}
const diffLines = added + deleted

// --- execution surface: lockfile (what got installed) ---
const lockPackages = lockfile?.packages
  ? Object.keys(lockfile.packages).filter((k) => k !== "").length
  : null
const directDeps = lockfile?.packages?.[""]?.dependencies
  ? Object.keys(lockfile.packages[""].dependencies).length
  : null

// --- execution surface: Jibril profile (what the run did) ---
let domains = []
let connections = null
let processes = new Set()
let lineageNodes = new Set()
let detections = new Set()
if (profile) {
  domains = profile.network?.egress?.domains ?? []
  const peers = profile.network?.egress?.peers ?? []
  connections = peers.length
  for (const peer of peers) {
    for (const det of peer.detections ?? []) if (det !== "flow") detections.add(det)
    for (const tree of peer.proc_trees ?? []) {
      if (tree.process) processes.add(`${tree.process}:${tree.executable ?? ""}`)
      for (const node of tree.ancestry ?? []) lineageNodes.add(node)
    }
  }
}

// Domain scoring. Only workload-relevant egress counts toward the coverage
// gap: GitHub-hosted runner/action infrastructure and the package registry
// baseline are expected on every run and must not pad the numbers (mirrors
// the RUNNER_STEP_BASELINE / WORKLOAD_BASELINE split in
// tools/pr-approval-agent/garnet_runtime.py).
const INFRA_EXACT = new Set(["github.com", "api.github.com", "codeload.github.com", "localhost"])
const INFRA_SUFFIXES = [".githubusercontent.com", ".githubapp", ".githubapp.com", ".actions.githubusercontent.com"]
const INFRA_PREFIXES = ["hosted-compute-", "glb-"]
const REGISTRY_BASELINE = new Set(["registry.npmjs.org"])
const isInfra = (d) =>
  INFRA_EXACT.has(d) || INFRA_SUFFIXES.some((s) => d.endsWith(s)) || INFRA_PREFIXES.some((p) => d.startsWith(p))
const infraDomains = domains.filter(isInfra)
const registryDomains = domains.filter((d) => !isInfra(d) && REGISTRY_BASELINE.has(d))
const workloadDomains = domains.filter((d) => !isInfra(d) && !REGISTRY_BASELINE.has(d))

const domainsInDiff = domains.filter((d) => patch.includes(d))
const n = (v) => (v === null || v === undefined ? "—" : String(v))

const lines = []
lines.push("<!-- npm-testbed-coverage-gap -->")
lines.push("### Static review surface vs execution surface")
lines.push("")
lines.push("What the diff shows a reviewer, next to what the run actually did under the Garnet sensor. Facts from this PR head's execution record; judgment stays with the reviewer.")
lines.push("")
lines.push("| | Static review (the diff) | Execution (the recorded run) |")
lines.push("| --- | --- | --- |")
lines.push(`| Lines | ${diffLines} changed (${added}+ / ${deleted}−) | — |`)
lines.push(`| Files / packages | ${files.length} file(s) touched | ${n(lockPackages)} package(s) installed (${n(directDeps)} direct) |`)
lines.push(`| Processes | 0 visible in diff | ${profile ? processes.size : "—"} recorded process(es), ${profile ? lineageNodes.size : "—"} distinct lineage node(s) |`)
lines.push(`| Outbound destinations | ${domainsInDiff.length} named in diff | ${profile ? `${workloadDomains.length} workload domain(s) beyond CI infra/registry (${domains.length} total)` : "—"}, ${n(connections)} connection(s) |`)
if (detections.size > 0) {
  lines.push(`| Detections | — | ${[...detections].sort().join(", ")} |`)
}
lines.push("")
if (domains.length > 0) {
  const unexplainedWorkload = workloadDomains.filter((d) => !domainsInDiff.includes(d))
  if (workloadDomains.length > 0) {
    lines.push(`Workload egress beyond CI infrastructure and the npm registry: ${workloadDomains.map((d) => `\`${d}\``).join(", ")}.`)
    lines.push(`${unexplainedWorkload.length} of ${workloadDomains.length} workload domain(s) appear nowhere in the diff — the diff alone cannot explain them.`)
  } else {
    lines.push("All recorded workload egress stayed within CI infrastructure and the npm registry baseline.")
  }
  const rest = [...registryDomains, ...infraDomains]
  if (rest.length > 0) {
    lines.push("")
    lines.push(`<sub>Baseline (not scored): registry ${registryDomains.map((d) => `\`${d}\``).join(", ") || "—"} · runner/CI infra ${infraDomains.map((d) => `\`${d}\``).join(", ")}</sub>`)
  }
} else if (profile) {
  lines.push("No outbound domains were recorded for this run.")
} else {
  lines.push("No execution record was available for this run (sensor profile missing) — absence of evidence, not a clean run.")
}
lines.push("")
lines.push("Cross-check against the **Garnet Runtime Review** comment on this PR (execution chains + destinations, per job) before finalizing a review — see `REVIEW.md`.")
if (process.env.HEAD_SHA) {
  lines.push("")
  lines.push(`<sub>Head \`${process.env.HEAD_SHA.slice(0, 12)}\` · rendered by \`npm-testbed/scripts/coverage-gap.mjs\`</sub>`)
}
console.log(lines.join("\n"))
